root: true
env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

rules:
  # `var`を使ったら怒るよ
  no-var: error

  # セミコロン抜かないで
  semi: error

  # `==` とかを使わないでね
  eqeqeq: error

  # カンマのあとはスペースを入れてくれ
  comma-spacing: error

  # インデントは2で守ってね
  indent:
    - error
    - 2

  # ブロック演算子はスペース入れてね
  block-spacing: error
  
  # `{}` の中の前後はスペースを入れてね
  object-curly-spacing:
    - error
    - always

  # 演算子の前後のスペースは絶対抜かないで
  space-infix-ops: error

  # アロー演算子前後のスペース強制
  arrow-spacing: error

  # タブとスペースを混ぜないで
  no-mixed-spaces-and-tabs: error
  
  max-len:
    - error
    - code: 80
      ignoreUrls: true
      ignorePattern: ^import\s.+\sfrom\s.+;$