name: test
on:
  pull_request:
    paths:
      - src/**/*
  push:
    branches:
      - master
    paths:
      - src/**/*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: using node
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - uses: pnpm/action-setup@v3
        with: 
          version: latest

      - run: pnpm install --frozen-lockfile

      - name: run tests
        run: pnpm test
